# Generated by Django 5.2.5 on 2025-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='company_avatars/'),
        ),
    ]
