# Generated by Django 5.2.5 on 2025-10-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0002_company_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Working student', 'Working student')], default='Full-time', max_length=50),
        ),
    ]
