# Generated by Django 5.2.7 on 2025-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reputation',
            field=models.FloatField(default=0.0),
        ),
    ]
