# Generated by assistant - add original_post field
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0005_userprofile_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='socialfeed.post'),
        ),
    ]
