# Generated by Django 5.2.7 on 2025-10-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0006_add_original_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stream_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
