# Generated by Django 5.2.7 on 2025-10-29 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0007_post_stream_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stream_key',
        ),
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow'), ('mention_post', 'Mention in Post'), ('mention_reply', 'Mention in Reply'), ('like_post', 'Like Post'), ('like_reply', 'Like Reply'), ('reply', 'Reply'), ('job_application', 'Job Application')], max_length=32),
        ),
    ]
