# Generated by Django 5.2.7 on 2025-10-29 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0008_remove_post_stream_key_job_applicants_job_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialfeed.job'),
        ),
    ]
