# Generated by Django 5.2.7 on 2025-10-29 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0009_notification_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialfeed.job'),
        ),
    ]
